/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthArchiveRouteImport } from './routes/_auth/archive'
import { Route as AuthAssignmentsRouteImport } from './routes/_auth/assignments'
import { Route as AuthAuditRouteImport } from './routes/_auth/audit'
import { Route as AuthClassesRouteImport } from './routes/_auth/classes'
import { Route as AuthColumnsRouteImport } from './routes/_auth/columns'
import { Route as AuthCoordinatorRouteImport } from './routes/_auth/coordinator'
import { Route as AuthImportRouteImport } from './routes/_auth/import'
import { Route as AuthLifecycleRouteImport } from './routes/_auth/lifecycle'
import { Route as AuthReportsRouteImport } from './routes/_auth/reports'
import { Route as AuthUsersRouteImport } from './routes/_auth/users'
import { Route as AuthStudentsIndexRouteImport } from './routes/_auth/students.index'
import { Route as AuthStudentsStudentIdHistoryRouteImport } from './routes/_auth/students.$studentId.history'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthArchiveRoute = AuthArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAssignmentsRoute = AuthAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuditRoute = AuthAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClassesRoute = AuthClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthColumnsRoute = AuthColumnsRouteImport.update({
  id: '/columns',
  path: '/columns',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCoordinatorRoute = AuthCoordinatorRouteImport.update({
  id: '/coordinator',
  path: '/coordinator',
  getParentRoute: () => AuthRoute,
} as any)
const AuthImportRoute = AuthImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLifecycleRoute = AuthLifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStudentsIndexRoute = AuthStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStudentsStudentIdHistoryRoute =
  AuthStudentsStudentIdHistoryRouteImport.update({
    id: '/students/$studentId/history',
    path: '/students/$studentId/history',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/archive': typeof AuthArchiveRoute
  '/assignments': typeof AuthAssignmentsRoute
  '/audit': typeof AuthAuditRoute
  '/classes': typeof AuthClassesRoute
  '/columns': typeof AuthColumnsRoute
  '/coordinator': typeof AuthCoordinatorRoute
  '/import': typeof AuthImportRoute
  '/lifecycle': typeof AuthLifecycleRoute
  '/reports': typeof AuthReportsRoute
  '/users': typeof AuthUsersRoute
  '/students/': typeof AuthStudentsIndexRoute
  '/students/$studentId/history': typeof AuthStudentsStudentIdHistoryRoute
}
export interface FileRoutesByTo {
  '/archive': typeof AuthArchiveRoute
  '/assignments': typeof AuthAssignmentsRoute
  '/audit': typeof AuthAuditRoute
  '/classes': typeof AuthClassesRoute
  '/columns': typeof AuthColumnsRoute
  '/coordinator': typeof AuthCoordinatorRoute
  '/import': typeof AuthImportRoute
  '/lifecycle': typeof AuthLifecycleRoute
  '/reports': typeof AuthReportsRoute
  '/users': typeof AuthUsersRoute
  '/': typeof AuthIndexRoute
  '/students': typeof AuthStudentsIndexRoute
  '/students/$studentId/history': typeof AuthStudentsStudentIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/archive': typeof AuthArchiveRoute
  '/_auth/assignments': typeof AuthAssignmentsRoute
  '/_auth/audit': typeof AuthAuditRoute
  '/_auth/classes': typeof AuthClassesRoute
  '/_auth/columns': typeof AuthColumnsRoute
  '/_auth/coordinator': typeof AuthCoordinatorRoute
  '/_auth/import': typeof AuthImportRoute
  '/_auth/lifecycle': typeof AuthLifecycleRoute
  '/_auth/reports': typeof AuthReportsRoute
  '/_auth/users': typeof AuthUsersRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/students/': typeof AuthStudentsIndexRoute
  '/_auth/students/$studentId/history': typeof AuthStudentsStudentIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/assignments'
    | '/audit'
    | '/classes'
    | '/columns'
    | '/coordinator'
    | '/import'
    | '/lifecycle'
    | '/reports'
    | '/users'
    | '/students/'
    | '/students/$studentId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/archive'
    | '/assignments'
    | '/audit'
    | '/classes'
    | '/columns'
    | '/coordinator'
    | '/import'
    | '/lifecycle'
    | '/reports'
    | '/users'
    | '/'
    | '/students'
    | '/students/$studentId/history'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/archive'
    | '/_auth/assignments'
    | '/_auth/audit'
    | '/_auth/classes'
    | '/_auth/columns'
    | '/_auth/coordinator'
    | '/_auth/import'
    | '/_auth/lifecycle'
    | '/_auth/reports'
    | '/_auth/users'
    | '/_auth/'
    | '/_auth/students/'
    | '/_auth/students/$studentId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/archive': {
      id: '/_auth/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthArchiveRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/assignments': {
      id: '/_auth/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthAssignmentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/audit': {
      id: '/_auth/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthAuditRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/classes': {
      id: '/_auth/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthClassesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/columns': {
      id: '/_auth/columns'
      path: '/columns'
      fullPath: '/columns'
      preLoaderRoute: typeof AuthColumnsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/coordinator': {
      id: '/_auth/coordinator'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof AuthCoordinatorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/import': {
      id: '/_auth/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthImportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/lifecycle': {
      id: '/_auth/lifecycle'
      path: '/lifecycle'
      fullPath: '/lifecycle'
      preLoaderRoute: typeof AuthLifecycleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports': {
      id: '/_auth/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/students/': {
      id: '/_auth/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthStudentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/students/$studentId/history': {
      id: '/_auth/students/$studentId/history'
      path: '/students/$studentId/history'
      fullPath: '/students/$studentId/history'
      preLoaderRoute: typeof AuthStudentsStudentIdHistoryRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthArchiveRoute: typeof AuthArchiveRoute
  AuthAssignmentsRoute: typeof AuthAssignmentsRoute
  AuthAuditRoute: typeof AuthAuditRoute
  AuthClassesRoute: typeof AuthClassesRoute
  AuthColumnsRoute: typeof AuthColumnsRoute
  AuthCoordinatorRoute: typeof AuthCoordinatorRoute
  AuthImportRoute: typeof AuthImportRoute
  AuthLifecycleRoute: typeof AuthLifecycleRoute
  AuthReportsRoute: typeof AuthReportsRoute
  AuthUsersRoute: typeof AuthUsersRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthStudentsIndexRoute: typeof AuthStudentsIndexRoute
  AuthStudentsStudentIdHistoryRoute: typeof AuthStudentsStudentIdHistoryRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthArchiveRoute: AuthArchiveRoute,
  AuthAssignmentsRoute: AuthAssignmentsRoute,
  AuthAuditRoute: AuthAuditRoute,
  AuthClassesRoute: AuthClassesRoute,
  AuthColumnsRoute: AuthColumnsRoute,
  AuthCoordinatorRoute: AuthCoordinatorRoute,
  AuthImportRoute: AuthImportRoute,
  AuthLifecycleRoute: AuthLifecycleRoute,
  AuthReportsRoute: AuthReportsRoute,
  AuthUsersRoute: AuthUsersRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthStudentsIndexRoute: AuthStudentsIndexRoute,
  AuthStudentsStudentIdHistoryRoute: AuthStudentsStudentIdHistoryRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
