"""core tables

Revision ID: 8840a6d43a2c
Revises:
Create Date: 2026-07-31 02:55:30.259174

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8840a6d43a2c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academic_years",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('setup','active','archived')", name=op.f("ck_academic_years_status_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_academic_years")),
        sa.UniqueConstraint("label", name=op.f("uq_academic_years_label")),
    )
    op.create_table(
        "students",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("school_number", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("search_name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
        sa.UniqueConstraint("school_number", name=op.f("uq_students_school_number")),
    )
    op.create_index(op.f("ix_students_search_name"), "students", ["search_name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_coordinator", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "school_classes",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("year_id", sa.BigInteger(), nullable=False),
        sa.Column("grade_level", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "grade_level BETWEEN 1 AND 8", name=op.f("ck_school_classes_grade_level_valid")
        ),
        sa.ForeignKeyConstraint(
            ["year_id"],
            ["academic_years.id"],
            name=op.f("fk_school_classes_year_id_academic_years"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_school_classes")),
        sa.UniqueConstraint(
            "year_id", "grade_level", "section", name=op.f("uq_school_classes_year_id")
        ),
    )
    op.create_table(
        "semesters",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("year_id", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('open','locked')", name=op.f("ck_semesters_status_valid")),
        sa.CheckConstraint("number IN (1, 2)", name=op.f("ck_semesters_number_valid")),
        sa.ForeignKeyConstraint(
            ["year_id"], ["academic_years.id"], name=op.f("fk_semesters_year_id_academic_years")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_semesters")),
        sa.UniqueConstraint("year_id", "number", name=op.f("uq_semesters_year_id")),
    )
    op.create_table(
        "student_languages",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("student_id", sa.BigInteger(), nullable=False),
        sa.Column("year_id", sa.BigInteger(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "language IN ('german','french')", name=op.f("ck_student_languages_language_valid")
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id"], name=op.f("fk_student_languages_student_id_students")
        ),
        sa.ForeignKeyConstraint(
            ["year_id"],
            ["academic_years.id"],
            name=op.f("fk_student_languages_year_id_academic_years"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_languages")),
        sa.UniqueConstraint("student_id", "year_id", name=op.f("uq_student_languages_student_id")),
    )
    op.create_table(
        "enrollments",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("student_id", sa.BigInteger(), nullable=False),
        sa.Column("year_id", sa.BigInteger(), nullable=False),
        sa.Column("class_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"], ["school_classes.id"], name=op.f("fk_enrollments_class_id_school_classes")
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id"], name=op.f("fk_enrollments_student_id_students")
        ),
        sa.ForeignKeyConstraint(
            ["year_id"], ["academic_years.id"], name=op.f("fk_enrollments_year_id_academic_years")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollments")),
        sa.UniqueConstraint("student_id", "year_id", name=op.f("uq_enrollments_student_id")),
    )
    op.create_table(
        "teaching_assignments",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("class_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "role IN ('main','skills','german','french')",
            name=op.f("ck_teaching_assignments_role_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["school_classes.id"],
            name=op.f("fk_teaching_assignments_class_id_school_classes"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_teaching_assignments_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teaching_assignments")),
        sa.UniqueConstraint("class_id", "role", name=op.f("uq_teaching_assignments_class_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teaching_assignments")
    op.drop_table("enrollments")
    op.drop_table("student_languages")
    op.drop_table("semesters")
    op.drop_table("school_classes")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_students_search_name"), table_name="students")
    op.drop_table("students")
    op.drop_table("academic_years")
    # ### end Alembic commands ###
