"""add phase 2 grade tables

Revision ID: ed892699e61d
Revises: 8840a6d43a2c
Create Date: 2026-08-04 17:16:38.444605

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ed892699e61d"
down_revision: str | Sequence[str] | None = "8840a6d43a2c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "column_definitions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("semester_id", sa.BigInteger(), nullable=False),
        sa.Column("grade_level", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("value_type", sa.String(), nullable=False),
        sa.Column("owner_role", sa.String(), nullable=False),
        sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("group_labels", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("counts_in_average", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "owner_role IN ('main','skills','german','french')",
            name=op.f("ck_column_definitions_owner_role_valid"),
        ),
        sa.CheckConstraint(
            "subject IN ('english', 'german', 'french')",
            name=op.f("ck_column_definitions_subject_valid"),
        ),
        sa.CheckConstraint(
            "value_type IN ('score','scale3','text')",
            name=op.f("ck_column_definitions_value_type_valid"),
        ),
        sa.CheckConstraint(
            "grade_level BETWEEN 1 AND 8", name=op.f("ck_column_definitions_grade_level_valid")
        ),
        sa.ForeignKeyConstraint(
            ["semester_id"],
            ["semesters.id"],
            name=op.f("fk_column_definitions_semester_id_semesters"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_column_definitions")),
    )
    op.create_table(
        "override_grants",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("class_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "role IN ('main','skills','german','french')",
            name=op.f("ck_override_grants_role_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["school_classes.id"],
            name=op.f("fk_override_grants_class_id_school_classes"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_override_grants_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_override_grants")),
        sa.UniqueConstraint("user_id", "class_id", "role", name=op.f("uq_override_grants_user_id")),
    )
    op.create_table(
        "save_batches",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("class_id", sa.BigInteger(), nullable=False),
        sa.Column("is_undo", sa.Boolean(), nullable=False),
        sa.Column("undone", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["school_classes.id"],
            name=op.f("fk_save_batches_class_id_school_classes"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_save_batches_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_save_batches")),
    )
    op.create_table(
        "audit_entries",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("batch_id", sa.BigInteger(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column("student_id", sa.BigInteger(), nullable=False),
        sa.Column("column_definition_id", sa.BigInteger(), nullable=False),
        sa.Column("old_existed", sa.Boolean(), nullable=False),
        sa.Column("old_score", sa.SmallInteger(), nullable=True),
        sa.Column("old_scale", sa.SmallInteger(), nullable=True),
        sa.Column("old_text", sa.String(), nullable=True),
        sa.Column("new_score", sa.SmallInteger(), nullable=True),
        sa.Column("new_scale", sa.SmallInteger(), nullable=True),
        sa.Column("new_text", sa.String(), nullable=True),
        sa.Column("forced", sa.Boolean(), nullable=False),
        sa.Column("via_grant_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_entries_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["save_batches.id"], name=op.f("fk_audit_entries_batch_id_save_batches")
        ),
        sa.ForeignKeyConstraint(
            ["column_definition_id"],
            ["column_definitions.id"],
            name=op.f("fk_audit_entries_column_definition_id_column_definitions"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id"], name=op.f("fk_audit_entries_student_id_students")
        ),
        sa.ForeignKeyConstraint(
            ["via_grant_id"],
            ["override_grants.id"],
            name=op.f("fk_audit_entries_via_grant_id_override_grants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_entries")),
    )
    op.create_table(
        "grade_values",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("student_id", sa.BigInteger(), nullable=False),
        sa.Column("column_definition_id", sa.BigInteger(), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=True),
        sa.Column("scale", sa.SmallInteger(), nullable=True),
        sa.Column("text_value", sa.String(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("scale BETWEEN 1 AND 3", name=op.f("ck_grade_values_scale_range")),
        sa.CheckConstraint("score BETWEEN 0 AND 100", name=op.f("ck_grade_values_score_range")),
        sa.ForeignKeyConstraint(
            ["column_definition_id"],
            ["column_definitions.id"],
            name=op.f("fk_grade_values_column_definition_id_column_definitions"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id"], name=op.f("fk_grade_values_student_id_students")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_grade_values_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grade_values")),
        sa.UniqueConstraint(
            "student_id", "column_definition_id", name=op.f("uq_grade_values_student_id")
        ),
    )
    op.create_index(
        op.f("ix_grade_values_column_definition_id"),
        "grade_values",
        ["column_definition_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_grade_values_column_definition_id"), table_name="grade_values")
    op.drop_table("grade_values")
    op.drop_table("audit_entries")
    op.drop_table("save_batches")
    op.drop_table("override_grants")
    op.drop_table("column_definitions")
    # ### end Alembic commands ###
