/**
 * The school's identity, for the web apps.
 *
 * Two layers (ADR-054):
 *
 *  1. Build-time defaults from `brand.json` and `logo.svg` next to this file,
 *     bundled into every build. The public demo and a fresh clone use these.
 *  2. A runtime overlay. `public/branding/brand.js` (generated by `pnpm brand`,
 *     replaced by a school's own file at deployment) runs before the app and
 *     sets `window.__FLRC_BRAND__`; the logo and favicon are served from the
 *     same folder. A school never rebuilds to rebrand.
 *
 * The bundled logo is imported as a module so the bundler fingerprints it and
 * serves it under the right base path (the admin app lives at `/admin/`).
 */
import brand from "../brand.json";
import logoUrl from "../logo.svg";

export type RuntimeBrand = {
  name?: string;
  shortName?: string;
  accentColor?: string;
  logoUrl?: string | null;
};

declare global {
  interface Window {
    __FLRC_BRAND__?: RuntimeBrand;
  }
}

const runtime: RuntimeBrand = (typeof window !== "undefined" && window.__FLRC_BRAND__) || {};
const clean = (value: string | undefined): string => (value ?? "").trim();

/** Full legal-ish name. Used for the PDF masthead and the browser title. */
export const SCHOOL_NAME: string = clean(runtime.name) || brand.name;

/** Shorter name for the top bar, where horizontal space is tight. */
export const SCHOOL_SHORT_NAME: string =
  clean(runtime.shortName) || clean(runtime.name) || brand.shortName || brand.name;

/** Runtime overlay logo when present, otherwise the fingerprinted bundled one. */
export const LOGO_URL: string = runtime.logoUrl || logoUrl;

/** The school's accent colour as hex. */
export const ACCENT_COLOR: string = clean(runtime.accentColor) || brand.accentColor;

export const BRAND = brand;
